#! /usr/bin/env ruby

require_relative 'app'

@actions = {
  '1' => :list_all_books,
  '2' => :list_all_people,
  '3' => :create_person,
  '4' => :create_book,
  '5' => :create_rental,
  '6' => :list_all_rentals,
  '7' => :exit
}

def main
  app = App.new
  status = true

  puts
  puts 'Welcome to school library App!'
  while status
    puts
    puts 'Please choose an option by enterin a number:'
    puts '1 - List all books'
    puts '2 - List all people'
    puts '3 - Create a person'
    puts '4 - Create a book'
    puts '5 - Create a rental'
    puts '6 - List  all rentals for a given person id'
    puts '7 - Exit'

    option = gets.chomp
    action = @actions[option]

    call_case(app, action) do
      status = false
    end
  end
end

def call_case(app, action)
  if action
    case action
    when :exit
      puts 'Thank you for using this app!'
      yield
    else
      app.send(action)
    end
  else
    puts 'Sorry, you choose a wrong option'
  end
end

main # Executable file
